name: Build, test and push the Docker images

on:
  pull_request:
    branches: [ '**' ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build images
      run: |
        docker build -t ecarocci/base:centos7.6 -f ./images/base/centos/7.6/base/Dockerfile .
        docker push ecarocci/base:centos7.6
        docker build -t ecarocci/base:centos7.6-ius -f ./images/base/centos/7.6/ius/Dockerfile .
        docker push ecarocci/base:centos7.6-ius
        docker build -t ecarocci/base:centos7.7 -f ./images/base/centos/7.7/base/Dockerfile .
        docker push ecarocci/base:centos7.7
        docker build -t ecarocci/base:centos7.7-remi -f ./images/base/centos/7.7/remi/Dockerfile .
        docker push ecarocci/base:centos7.7-remi